import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    backgroundColor: '#f0f3ff',
  },
  header: {
    backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    backgroundColor: '#6366f1',
    paddingTop: 60,
    paddingBottom: 25,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#ffffff',
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  
  // Search and Sort Styles
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 15,
    marginHorizontal: 20,
    marginTop: 20,
    paddingHorizontal: 18,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    height: 50,
    fontSize: 16,
    color: '#374151',
    fontWeight: '500',
  },
  clearButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
  },
  sortContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 18,
    marginBottom: 15,
  },
  sortLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#374151',
    marginRight: 15,
  },
  sortOptions: {
    flex: 1,
  },
  sortButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    backgroundColor: '#ffffff',
    borderRadius: 25,
    marginRight: 12,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  sortButtonActive: {
    backgroundColor: '#6366f1',
    borderColor: '#6366f1',
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  sortButtonText: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '600',
  },
  sortButtonTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  resultsHeader: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  resultsCount: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '600',
  },

  // Card Styles
  cardList: {
    padding: 20,
    paddingTop: 10,
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 20,
    padding: 24,
    marginBottom: 18,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#f1f5f9',
    overflow: 'hidden',
    position: 'relative',
  },
  urgentCard: {
    borderLeftWidth: 5,
    borderLeftColor: '#ef4444',
    backgroundColor: '#fef7f7',
    shadowColor: '#ef4444',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  companyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  companyName: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1f2937',
    flex: 1,
    marginLeft: 12,
    letterSpacing: 0.3,
  },
  discountBadge: {
    backgroundColor: 'linear-gradient(135deg, #ec4899, #ef4444)',
    backgroundColor: '#ec4899',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: 'center',
    minWidth: 80,
    shadowColor: '#ec4899',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  discountText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  discountAmount: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  discountType: {
    color: '#ffffff',
    fontSize: 11,
    marginTop: 2,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  offerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 10,
    lineHeight: 26,
  },
  offerDescription: {
    fontSize: 15,
    color: '#6b7280',
    lineHeight: 22,
    marginBottom: 14,
    fontWeight: '500',
  },
  offer: {
    fontSize: 16,
    color: '#374151',
    lineHeight: 24,
    marginBottom: 18,
    fontWeight: '500',
  },
  cardDetails: {
    marginBottom: 10,
  },
  mainCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0fdf4',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#22c55e',
    shadowColor: '#22c55e',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  mainCodeLabel: {
    fontSize: 12,
    color: '#16a34a',
    marginLeft: 8,
    marginRight: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  mainCodeText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1f2937',
    fontFamily: 'monospace',
    flex: 1,
    letterSpacing: 1,
  },
  copyButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#dcfce7',
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  tapForMore: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  expiryInfo: {
    flex: 1,
  },
  expiryContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  expiryDate: {
    fontSize: 14,
    color: '#666',
    marginBottom: 2,
  },
  expiryText: {
    fontSize: 12,
    color: '#666',
    marginLeft: 4,
  },
  daysLeft: {
    fontSize: 12,
    fontWeight: '600',
  },
  urgentExpiry: {
    color: '#ff6b6b',
  },
  normalExpiry: {
    color: '#4CAF50',
  },
  expiredExpiry: {
    color: '#999',
  },
  urgentText: {
    color: '#FF5722',
    fontWeight: '600',
  },
  minPurchase: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  urgencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF5722',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  urgencyText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 4,
    textTransform: 'uppercase',
  },
  viewDetailsButton: {
    backgroundColor: 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    backgroundColor: '#6366f1',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  viewDetailsText: {
    color: '#ffffff',
    fontWeight: '700',
    marginRight: 6,
    fontSize: 15,
    letterSpacing: 0.3,
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    maxHeight: '90%',
    minHeight: '60%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 25,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
    backgroundColor: '#fafbff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1f2937',
    flex: 1,
    letterSpacing: 0.5,
  },
  closeButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#f3f4f6',
  },
  modalBody: {
    flex: 1,
    padding: 25,
  },
  modalDiscountBadge: {
    backgroundColor: 'linear-gradient(135deg, #ec4899, #ef4444)',
    backgroundColor: '#ec4899',
    alignSelf: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 30,
    shadowColor: '#ec4899',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  modalDiscountText: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 22,
    letterSpacing: 0.5,
  },
  modalDiscountType: {
    color: '#ffffff',
    fontSize: 12,
    marginTop: 3,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  modalSection: {
    marginBottom: 28,
    backgroundColor: '#fafbff',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  modalSectionTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#1f2937',
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  modalOfferText: {
    fontSize: 16,
    color: '#374151',
    lineHeight: 26,
    fontWeight: '500',
  },
  modalExpiryDate: {
    fontSize: 17,
    color: '#1f2937',
    fontWeight: '600',
    marginBottom: 8,
  },
  modalDaysLeft: {
    fontSize: 15,
    fontWeight: '700',
  },
  urgentText: {
    color: '#ef4444',
  },
  normalText: {
    color: '#22c55e',
  },
  modalTermsText: {
    fontSize: 15,
    color: '#6b7280',
    lineHeight: 22,
    fontWeight: '500',
  },
  couponCodeContainer: {
    backgroundColor: '#f8fafc',
    padding: 20,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#6366f1',
    borderStyle: 'dashed',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  couponCodeText: {
    fontSize: 20,
    fontWeight: '800',
    color: '#6366f1',
    textAlign: 'center',
    letterSpacing: 3,
    fontFamily: 'monospace',
  },
  modalActions: {
    padding: 25,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    gap: 15,
    backgroundColor: '#fafbff',
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    gap: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
  },
  primaryButton: {
    backgroundColor: '#6366f1',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#6366f1',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  secondaryButtonText: {
    color: '#6366f1',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  noLinksText: {
    textAlign: 'center',
    color: '#9ca3af',
    fontSize: 15,
    fontStyle: 'italic',
    paddingVertical: 25,
    fontWeight: '500',
  },

  // Loading and Error States
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f0f3ff',
  },
  loadingText: {
    marginTop: 20,
    fontSize: 17,
    color: '#6b7280',
    fontWeight: '600',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 25,
    backgroundColor: '#f0f3ff',
  },
  errorText: {
    fontSize: 17,
    color: '#ef4444',
    textAlign: 'center',
    marginBottom: 25,
    fontWeight: '600',
    lineHeight: 24,
  },
  retryButton: {
    backgroundColor: '#6366f1',
    paddingHorizontal: 35,
    paddingVertical: 16,
    borderRadius: 16,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  
  // Empty State
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 45,
  },
  emptyText: {
    fontSize: 19,
    color: '#6b7280',
    textAlign: 'center',
    marginTop: 25,
    fontWeight: '600',
    lineHeight: 26,
  },
  emptySubtext: {
    fontSize: 15,
    color: '#9ca3af',
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '500',
    lineHeight: 22,
  },
});
